### ISSUE TITLE
resolv.rb:164:in `<class:Resolv>': uninitialized constant Timeout::Error (NameError)

### ISSUE THREAD

**Issue by christophprokop** [mozilla/ssh_scan#140] opened 2016-09-01 08:17 UTC
Hi there,

i compiled (core) ruby and then installed ssh_scan via
`$ gem install ssh_scan`
It works just fine with version 0.0.9 and 0.0.10, but when i try to execute ssh_scan in version 0.0.11 (e.g. with -h flag) i get:

```
$ /usr/local/ruby/2.3.1/bin/ssh_scan -h
/usr/local/ruby/2.3.1/lib/ruby/2.3.0/resolv.rb:164:in `<class:Resolv>': uninitialized constant Timeout::Error (NameError)
Did you mean?  KeyError
               IOError
               Errno
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/resolv.rb:39:in `<top (required)>'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/gems/2.3.0/gems/ssh_scan-0.0.11/lib/string_ext.rb:2:in `<top (required)>'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/gems/2.3.0/gems/ssh_scan-0.0.11/lib/ssh_scan/constants.rb:1:in `<top (required)>'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/gems/2.3.0/gems/ssh_scan-0.0.11/lib/ssh_scan.rb:6:in `<top (required)>'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/ruby/2.3.1/lib/ruby/gems/2.3.0/gems/ssh_scan-0.0.11/bin/ssh_scan:9:in `<top (required)>'
        from /usr/local/ruby/2.3.1/bin/ssh_scan:23:in `load'
        from /usr/local/ruby/2.3.1/bin/ssh_scan:23:in `<main>'

```

**Comment by jinankjain** [comment] 2016-09-01 16:57
@christophprokop This error is kind of strange I just did a fresh gem install ssh_scan and installed the newest version. I am not getting such error. Could you please elaborate on which OS you are running? So that I would be able to track the problem in a better way.

**Comment by claudijd** [comment] 2016-09-01 18:39
Also the output of these commands would help us triage...

ruby -v
gem list

**Comment by claudijd** [comment] 2016-09-01 18:45
What's also a littel bizzare about the exception is the line it's triggering on...

https://github.com/mozilla/ssh_scan/blob/master/bin/ssh_scan#L23

With that said, we probably should look at any code that has Resolv usage and make sure we're loading it.  Could be a order of operations loading issue or something.

**Comment by claudijd** [comment] 2016-09-01 18:47
Ok, I think I know where the bug is, standby

**Comment by jinankjain** [comment] 2016-09-01 18:47
@claudijd Only string_ext.rb uses resolv library

**Comment by claudijd** [comment] 2016-09-01 18:48
yep, that's where the bug is, we don't do exception handling on timeouts for resolve_fqdn_as_ipv6 or resolve_fqdn_as_ipv4

**Comment by claudijd** [comment] 2016-09-01 18:48
we need to trap those for timeout exceptions and make sure we load timeout at the top, will send a PR shortly

**Comment by jinankjain** [comment] 2016-09-01 18:49
@claudijd but with -h flag we should not have any timeout issues. And I installed the new gem on my machine it was working fine

**Comment by claudijd** [comment] 2016-09-01 18:55
I think what we should do is add the exception handling, which is a gap and then maybe get a pre-release out to @christophprokop to try and see what happens next.  Maybe there is some context we're missing here.

**Comment by claudijd** [comment] 2016-09-01 19:02
I proposed #143 as a potential fix.  I'll gen a beta gem release and see if @christophprokop is willing to try it again and see if that's the bug or if we can get a better exception case to work on.

**Comment by claudijd** [comment] 2016-09-01 19:06
I've published the gem beta version of "0.0.12.beta.1" for testing.

it can be installed via this command:

    gem install --pre -v="0.0.12.beta.1" ssh_scan

You might also consider removing all other versions of ssh_scan before doing so in the case they are fighting with each other.  That can be done by running this command...

    $ gem uninstall ssh_scan
    Remove executables:
    	ssh_scan

    in addition to the gem? [Yn]  y
    Removing ssh_scan
    Successfully uninstalled ssh_scan-0.0.11

**Comment by claudijd** [comment] 2016-09-01 19:09
Additionally, we might be looking at a ruby problem.  It will be interesting to know what @christophprokop comes back with.  Here's the line from Ruby 2.3.1...

    164:  class ResolvTimeout < Timeout::Error; end

**Comment by jinankjain** [comment] 2016-09-01 19:11
@claudijd I figured out that it is specifically failing on linux machine not on mac machines. I tried this new patch on Debian and it is getting the same errors. 

Interesting part is running the code from installed gem is causing problem but running from source code works fine 😕

**Comment by claudijd** [comment] 2016-09-01 19:25
@jinankjain that makes me think it's a path loading bug.  If you have it failing only on the gem, I would edit the gem source directly and add a debug statement in there.

**Comment by jinankjain** [comment] 2016-09-01 19:33
@claudijd One more interesting thing I found is from zsh I login into /bin/bash and then tried installing this gem and run the ssh_scan -h it was working.

**Comment by christophprokop** [comment] 2016-09-01 19:39
(sorry for not providing this in the first place:)

the error occured to me on CentOS (Red Hat) 6.7 and on opensuse 13.1
On both machines ruby was compiled and only the dependencies were installed for certlint and ssh_scan

```
prokop@suse13.1 $ /usr/local/ruby/2.3.1/bin/ruby -v 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

prokop@suse13.1 $ /usr/local/ruby/2.3.1/bin/gem list   
*** LOCAL GEMS ***
bigdecimal (1.2.8)
bindata (2.3.1)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-ssh (3.2.0)
net-telnet (0.1.1)
netaddr (1.5.1)
open4 (1.3.4)
power_assert (0.2.6)
psych (2.0.17)
public_suffix (1.5.3)
rake (10.4.2)
rdoc (4.2.1)
simpleidn (0.0.7)
ssh_scan (0.0.11)
test-unit (3.1.5)
timeout (0.0.1)
timeout-extensions (0.1.1)
```

**Comment by claudijd** [comment] 2016-09-01 19:47
Added integration tests in https://github.com/mozilla/ssh_scan/pull/145 to make sure this case doesn't happen again.  Linux is our primary deployment OS and we don't want that breaking.

**Comment by jinankjain** [comment] 2016-09-01 19:49
@claudijd Build failed as expected.

**Comment by claudijd** [comment] 2016-09-01 19:50
yep https://travis-ci.org/mozilla/ssh_scan/jobs/156910570

**Comment by christophprokop** [comment] 2016-09-01 19:58
pre release "0.0.12.beta.1" brings up the same error

**Comment by claudijd** [comment] 2016-09-01 20:11
@christophprokop thanks for the feedback, we can repro now, we'll figure out what the issue is and get a complete patch working soon.  We've also added tests to make sure this doesn't happen again.   For now, maybe got back to using 0.0.10 until we've got this worked out.

**Comment by christophprokop** [comment] 2016-09-01 20:16
@claudijd ok, thank you!

**Comment by claudijd** [comment] 2016-09-01 21:41
@christophprokop @jinankjain i believe I've fixed this bug in #147  I think the core of the issue was the addition of the timeout dependancy in the gem spec which was unnecessary because timeout is part of stdlib.

I've produced a beta gem release v0.0.12.beta.2 for us to try out...

    gem install --pre -v="0.0.12.beta.2" ssh_scan

That should do the trick, please verify and I'll release 0.0.12 as a bug fix release because this is sort of an annoying bug we don't want people to have to sit with.

**Comment by jinankjain** [comment] 2016-09-01 22:00
@claudijd I reached at the same conclusion and then I had some meeting I had leave for that. Name  space collision might be causing such trouble

**Comment by christophprokop** [comment] 2016-09-01 22:00
@claudijd Great! 0.0.12.beta.2 works just fine! Thanks!

**Closed** 2016-09-02 01:46 UTC
Labels: bug

**Comment by claudijd** [comment] 2016-09-02 01:55
Fixed in https://github.com/mozilla/ssh_scan/releases/tag/0.0.12

**Comment by christophprokop** [comment] 2016-09-02 05:29
Great! Thank you!
