### ISSUE TITLE
Cipher compliance should be implementation independant (cipher == cipher@implementation => true)

### ISSUE THREAD

**Issue by exploide** [mozilla/ssh_scan#405] opened 2017-07-16 14:05 UTC
Just scanned a machine and it recommends "Remove these key exchange algorithms: curve25519-sha256". Since this is probably the best one, it should not be removed. I guess this happens because ssh_scan is only aware of `curve25519-sha256@libssh.org` (including the @... part).

**Comment by floatingatoll** [comment] 2017-07-16 15:37
For the record - which precise builds of your software combination are you
using (of SSH and SSL libraries) that advertises the cipher without the @
suffix?

**Comment by exploide** [comment] 2017-07-16 18:10
It is:

```
# cat /etc/redhat-release 
Fedora release 26 (Twenty Six)
# ssh -Version
OpenSSH_7.5p1, OpenSSL 1.1.0f-fips  25 May 2017
```

Actually, it advertises both, `curve25519-sha256` and `curve25519-sha256@libssh.org`.

From the changelogs of [OpenSSH 7.4](https://www.openssh.com/txt/release-7.4):

> sshd(8), ssh(1): Support the "curve25519-sha256" key exchange
   method. This is identical to the currently-supported method named
   "curve25519-sha256@libssh.org".

**Comment by claudijd** [comment] 2017-07-20 14:18
I will try to fix this today and have it resolved.

My basic plan is this...

Make ciphers a Ruby object instead of a string so I can defined their comparability such that curve25519-sha256 == curve25519-sha256@foo => true

This shouldn't be that involved and I'll update folks when I'm done.

**Comment by claudijd** [comment] 2017-07-20 15:47
This is also a duplicate of https://github.com/mozilla/ssh_scan_api/issues/79, but since the fix is in the ssh_scan lib I'll keep this as a parent and link so the other reporter has visibility that a fix is underway.

**Closed** 2017-07-20 15:48 UTC
Labels: bug
